# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\01.CORAL\03.STATUS\status\status.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_status(object):
    def setupUi(self, status):
        status.setObjectName("status")
        status.resize(993, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../01.ALKIS_CODE/02.PHOTO/MILK_24X24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        status.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(status)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.onoma = QtWidgets.QComboBox(self.centralwidget)
        self.onoma.setObjectName("onoma")
        self.onoma.addItem("")
        self.onoma.addItem("")
        self.onoma.addItem("")
        self.onoma.addItem("")
        self.gridLayout.addWidget(self.onoma, 1, 0, 1, 2)
        self.work = QtWidgets.QComboBox(self.centralwidget)
        self.work.setObjectName("work")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.work.addItem("")
        self.gridLayout.addWidget(self.work, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 6, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 8, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 9, 1, 1)
        self.txt_onoma = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_onoma.setObjectName("txt_onoma")
        self.gridLayout.addWidget(self.txt_onoma, 2, 0, 1, 2)
        self.txt_work = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_work.setObjectName("txt_work")
        self.gridLayout.addWidget(self.txt_work, 2, 2, 1, 1)
        self.txt_posot = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_posot.setObjectName("txt_posot")
        self.gridLayout.addWidget(self.txt_posot, 2, 3, 1, 1)
        self.shmera_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.shmera_2.setObjectName("shmera_2")
        self.gridLayout.addWidget(self.shmera_2, 2, 5, 1, 1)
        self.txt_apo = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_apo.setInputMethodHints(QtCore.Qt.ImhTime)
        self.txt_apo.setObjectName("txt_apo")
        self.gridLayout.addWidget(self.txt_apo, 2, 6, 1, 2)
        self.txt_ews = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_ews.setObjectName("txt_ews")
        self.gridLayout.addWidget(self.txt_ews, 2, 8, 1, 1)
        self.diarkeia = QtWidgets.QLineEdit(self.centralwidget)
        self.diarkeia.setObjectName("diarkeia")
        self.gridLayout.addWidget(self.diarkeia, 2, 9, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.txt_parat = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_parat.setObjectName("txt_parat")
        self.gridLayout.addWidget(self.txt_parat, 4, 0, 1, 10)
        self.preview = QtWidgets.QPushButton(self.centralwidget)
        self.preview.setObjectName("preview")
        self.gridLayout.addWidget(self.preview, 5, 0, 1, 1)
        self.addrow = QtWidgets.QPushButton(self.centralwidget)
        self.addrow.setObjectName("addrow")
        self.gridLayout.addWidget(self.addrow, 6, 0, 1, 1)
        self.auto_2 = QtWidgets.QPushButton(self.centralwidget)
        self.auto_2.setObjectName("auto_2")
        self.gridLayout.addWidget(self.auto_2, 6, 4, 1, 3)
        self.deleterow = QtWidgets.QPushButton(self.centralwidget)
        self.deleterow.setObjectName("deleterow")
        self.gridLayout.addWidget(self.deleterow, 6, 7, 1, 2)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 6, 9, 1, 1)
        self.excel = QtWidgets.QTableWidget(self.centralwidget)
        self.excel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.excel.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.excel.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.excel.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.excel.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.excel.setRowCount(0)
        self.excel.setColumnCount(7)
        self.excel.setObjectName("excel")
        item = QtWidgets.QTableWidgetItem()
        self.excel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.excel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.excel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.excel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.excel.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.excel.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.excel.setHorizontalHeaderItem(6, item)
        self.excel.horizontalHeader().setCascadingSectionResizes(True)
        self.excel.horizontalHeader().setDefaultSectionSize(90)
        self.excel.horizontalHeader().setHighlightSections(True)
        self.excel.horizontalHeader().setMinimumSectionSize(26)
        self.excel.horizontalHeader().setStretchLastSection(True)
        self.excel.verticalHeader().setCascadingSectionResizes(True)
        self.excel.verticalHeader().setDefaultSectionSize(25)
        self.excel.verticalHeader().setMinimumSectionSize(20)
        self.excel.verticalHeader().setSortIndicatorShown(False)
        self.excel.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.excel, 7, 0, 1, 10)
        self.browse_xl = QtWidgets.QPushButton(self.centralwidget)
        self.browse_xl.setObjectName("browse_xl")
        self.gridLayout.addWidget(self.browse_xl, 8, 0, 1, 1)
        self.submit_excel = QtWidgets.QPushButton(self.centralwidget)
        self.submit_excel.setObjectName("submit_excel")
        self.gridLayout.addWidget(self.submit_excel, 8, 9, 1, 1)
        self.xl_directory = QtWidgets.QTextBrowser(self.centralwidget)
        self.xl_directory.setMinimumSize(QtCore.QSize(0, 30))
        self.xl_directory.setMaximumSize(QtCore.QSize(16777215, 30))
        self.xl_directory.setObjectName("xl_directory")
        self.gridLayout.addWidget(self.xl_directory, 8, 1, 1, 8)
        self.about = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.about.setFont(font)
        self.about.setObjectName("about")
        self.gridLayout.addWidget(self.about, 5, 9, 1, 1)
        status.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(status)
        self.statusbar.setObjectName("statusbar")
        status.setStatusBar(self.statusbar)
        self.send = QtWidgets.QAction(status)
        self.send.setObjectName("send")

        self.retranslateUi(status)
        self.onoma.currentTextChanged['QString'].connect(self.txt_onoma.setText)
        self.work.currentTextChanged['QString'].connect(self.txt_work.setText)
        self.clear.clicked.connect(self.excel.clear)
        QtCore.QMetaObject.connectSlotsByName(status)

    def retranslateUi(self, status):
        _translate = QtCore.QCoreApplication.translate
        status.setWindowTitle(_translate("status", "STATUS_A_TMHMAΤΟΣ"))
        self.label_2.setText(_translate("status", "ΧΡΗΣΤΗΣ"))
        self.label_3.setText(_translate("status", "WORK"))
        self.onoma.setItemText(0, _translate("status", "ΠΟΛΥΖΟΥΔΗΣ ΧΡΥΣΟΣΤΟΜΟΣ"))
        self.onoma.setItemText(1, _translate("status", "ΑΜΑΝΑΤΙΔΗΣ ΑΛΚΙΒΙΑΔΗΣ"))
        self.onoma.setItemText(2, _translate("status", "ΑΔΑΜΙΔΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ"))
        self.onoma.setItemText(3, _translate("status", "ΘΕΟΦΑΝΗΣ ΚΩΝΤΑΝΤΙΝΟΥ"))
        self.work.setToolTip(_translate("status", "ΔΙΑΛΕΞΕ ΠΕΡΙΓΡΑΦΗ"))
        self.work.setItemText(0, _translate("status", "ΠΑΡΑΤΗΡΗΣΕΙΣ"))
        self.work.setItemText(1, _translate("status", "NESTING-ΣΧΕΔΙΑ"))
        self.work.setItemText(2, _translate("status", "ΣΧΕΔΙΑΣΗ R/D"))
        self.work.setItemText(3, _translate("status", "ΣΧΕΔΙΑΣΗ ΠΡΟΪΟΝΤΩΝ MILKPLAN"))
        self.work.setItemText(4, _translate("status", "ΣΧΕΔΙΑΣΗ ΕΙΔΙΚΩΝ ΠΡΟΪΟΝΤΩΝ MILKPLAN"))
        self.work.setItemText(5, _translate("status", "ΣΧΕΔΙΑΣΗ ΦΑΣΟΝ"))
        self.work.setItemText(6, _translate("status", "ΒΛΑΒΗ"))
        self.work.setItemText(7, _translate("status", "ΑΡΧΕΙΟΘΕΤΗΣΗ ΚΩΔΙΚΩΝ - ΣΧΕΔΙΩΝ"))
        self.work.setItemText(8, _translate("status", "ΥΠΟΛΟΓΙΣΜΟΣ Α΄ ΥΛΗΣ"))
        self.work.setItemText(9, _translate("status", "ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΣ ΠΑΡΑΓΩΓΗΣ"))
        self.work.setItemText(10, _translate("status", "ΚΟΣΤΟΛΟΓΙΑ"))
        self.work.setItemText(11, _translate("status", "ΠΑΡΑΚΟΛΟΥΘΗΣΗ ΠΑΡΑΓΩΓΗΣ"))
        self.work.setItemText(12, _translate("status", "ΠΡΟΣΦΟΡΑ FASON"))
        self.work.setItemText(13, _translate("status", "ΠΡΟΣΦΟΡΑ ΕΡΓΑΖΟΜΕΝΩΝ MILKPLAN"))
        self.work.setItemText(14, _translate("status", "ΒΕΛΤΙΩΣΕΙΣ"))
        self.work.setItemText(15, _translate("status", "ΔΙΑΛΕΙΜΜΑ"))
        self.work.setItemText(16, _translate("status", "ΑΔΕΙΑ"))
        self.work.setItemText(17, _translate("status", "ΑΣΘΕΝΙΑ"))
        self.label_5.setText(_translate("status", "ΠΟΣ."))
        self.label.setText(_translate("status", "ΗΜΕΡ."))
        self.label_6.setText(_translate("status", "ΑΠΟ"))
        self.label_7.setText(_translate("status", "ΕΩΣ"))
        self.label_8.setText(_translate("status", "ΔΙΑΡΚΕΙΑ"))
        self.label_4.setText(_translate("status", "ΠΑΡΑΤΗΡΗΣΕΙΣ"))
        self.preview.setToolTip(_translate("status", "ΠΑΤΗΣΤΕ ΟΤΑΝ ΟΛΟΚΛΗΡΩΘΕΙ Η ΕΡΓΑΣΙΑ ΣΑΣ"))
        self.preview.setText(_translate("status", "PREVIEW"))
        self.addrow.setToolTip(_translate("status", "ΠΑΤΗΣΤΕ ΓΙΑ ΝΑ ΠΕΡΑΣΤΕΙ ΣΤΗΝ ΛΙΣΤΑ"))
        self.addrow.setText(_translate("status", "+"))
        self.auto_2.setToolTip(_translate("status", "ΠΡΟΒΛΕΨΕΙΣ ΜΕΡΑΣ"))
        self.auto_2.setText(_translate("status", "AUTO"))
        self.deleterow.setToolTip(_translate("status", "ΔΙΑΓΡΑΦΗ ΤΗΝ ΕΠΕΛΕΓΜΕΝΗ ΣΕΙΡΑ"))
        self.deleterow.setText(_translate("status", "ΔΙΑΓΡΑΨΕ ΣΕΙΡΑ"))
        self.clear.setToolTip(_translate("status", "ΣΒΗΝΕΙ ΟΛΕΣ ΤΙΣ ΚΑΤΑΧΩΡΗΣΕΙΣ"))
        self.clear.setText(_translate("status", "CLEAR_ALL"))
        self.excel.setSortingEnabled(True)
        item = self.excel.horizontalHeaderItem(0)
        item.setText(_translate("status", "ONOMA"))
        item = self.excel.horizontalHeaderItem(1)
        item.setText(_translate("status", "ΠΕΡΙΓΡΑΦΗ"))
        item = self.excel.horizontalHeaderItem(2)
        item.setText(_translate("status", "ΠΟΣ."))
        item = self.excel.horizontalHeaderItem(3)
        item.setText(_translate("status", "ΗΜΕΡ."))
        item = self.excel.horizontalHeaderItem(4)
        item.setText(_translate("status", "ΑΠΟ"))
        item = self.excel.horizontalHeaderItem(5)
        item.setText(_translate("status", "ΕΩΣ"))
        item = self.excel.horizontalHeaderItem(6)
        item.setText(_translate("status", "ΠΑΡΑΤΗΡΗΣΕΙΣ"))
        self.browse_xl.setToolTip(_translate("status", "ΔΙΑΛΕΞΤΕ ΤΟ EXCEL ΠΟΥ ΘΕΛΕΤΕ ΝΑ ΜΠΟΥΝ ΟΙ ΚΑΤΑΧΩΡΗΣΕΙΣ"))
        self.browse_xl.setText(_translate("status", "ΑΝΟΙΞΕ ΤΟ ΑΡΧΕΙΟ"))
        self.submit_excel.setToolTip(_translate("status", "ΑΠΟΘΗΚΕΥΣΗ ΣΤΟ EXCEL ΠΑΤΗΣΤΕ ΜΙΑ ΦΟΡΑ"))
        self.submit_excel.setText(_translate("status", "ΑΠΟΣΤΟΛΗ ΣΤΟ EXCEL"))
        self.about.setToolTip(_translate("status", "ΠΡΟΒΛΕΨΕΙΣ ΜΕΡΑΣ"))
        self.about.setText(_translate("status", "about"))
        self.send.setText(_translate("status", "send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    status = QtWidgets.QMainWindow()
    ui = Ui_status()
    ui.setupUi(status)
    status.show()
    sys.exit(app.exec_())
